import Head from 'next/head'
import Header from './../components/Header'
import Landing from './../components/Landing'
import Features from './../components/Features'
import Download from './../components/Download'
import FAQ from './../components/FAQ'
import Contact from './../components/Contact'
import Footer from './../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Bookmark - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Landing />
      <Features />
      <Download />
      <FAQ />
      <Contact />
      <Footer />
    </>
  )
}
